name: tests

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.sha }}
  cancel-in-progress: ${{ contains(github.ref, 'refs/tags/') }}

jobs:
  run_tests:
    strategy:
      fail-fast: true
      matrix:
        os-python-node:
          - [ubuntu-20.04, "3.7",  "20"]
          - [ubuntu-20.04, "3.8",  "20"]
          - [ubuntu-20.04, "3.9",  "20"]
          - [ubuntu-20.04, "3.10", "20"]
          - [ubuntu-20.04, "3.11", "20"]
          - [ubuntu-20.04, "3.12", "20"]
          - [ubuntu-20.04, "3.13", "20"]
    runs-on: ${{ matrix.os-python-node[0] }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.os-python-node[2] }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.os-python-node[1] }}

      - name: run tests
        if: ${{ matrix.os-python-node[1] != '3.9' }}
        run: |
          npm install -D typescript@~5.3
          pip install -r ci-requirements/requirements${{ matrix.os-python-node[1] }}.out
          pip install -e .
          pytest --benchmark-skip --no-cov

      - name: run tests & lint
        if: ${{ matrix.os-python-node[1] == '3.9' }}
        run: |
          npm install -D typescript@~5.3
          pip install -r ci-requirements/requirements${{ matrix.os-python-node[1] }}.out
          black src tests --check
          isort src tests --check
          ruff check src
          mypy --check-untyped-defs src
          pip install -e .
          pytest --benchmark-skip --no-cov

  build_sdist_n_wheel:
    name: Build source distribution
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - run_tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: upload coverage
        run: |
          npm install -D typescript@~5.3
          pip install -r ci-requirements/requirements3.9.out
          pip install -e .
          pytest --benchmark-skip --cov-append
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

      - name: build sdist
        run: |
          pip install -U pip build
          python -m build --sdist
          python -m build --wheel

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-sdist
          path: |
            ./dist/*.tar.gz
            ./dist/*.whl


  pypi-publish:
    name: Upload release to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build_sdist_n_wheel
    runs-on: ubuntu-20.04
    environment:
      name: pypi
      url: https://pypi.org/p/synclane
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          path: dist/
          pattern: artifact-*
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
